New(tests): Basic tests (login, logout) for RHOSR
redhat-developer/consoledot-e2e pull request #85
Opened 2023-01-25 14:10 UTC by rkubis

2023-01-25 14:28 UTC, kornys requested changes
please remove duplicate test

2023-01-25 14:46 UTC, rkubis commented on tests/rhosr/basic.spec.ts
> +test('perform login and logout', async ({ page }) => {
Test in parent directory is a little bit RHOSAK specific, it tests that user is able to see landing page of RHOSAK.

This duplicate test is RHOSR specific, it tests that user is able to see landing page of RHOSR.

Probably two options here:

1. Rewrite both tests to be product-unspecific.
2. Rename test(s) to something like "landing page present/shown".

2023-01-26 06:27 UTC, kornys commented on tests/rhosr/basic.spec.ts
> +test('perform login and logout', async ({ page }) => {
Well the first test do a login which is ok
Im talking about the second one which is definitely the same.

2023-01-26 07:38 UTC, rkubis commented on tests/rhosr/basic.spec.ts
> +test('perform login and logout', async ({ page }) => {
Ah, you are right, I am going to remove this duplication. Sorry, I thought that comment is about first one/both tests.

2023-01-26 08:13 UTC, kornys approved these changes

2023-01-26 08:53 UTC, Frawless approved these changes

2023-01-26 08:56 UTC, merged